version: "3.8"

services:

  vina-db:
    container_name: vina-db
    build: ./database/
    env_file: ./.env
    ports:
      - "27017:27017"
    volumes:
      - ./database/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./database/schema.json:/docker-entrypoint-initdb.d/schema.json:ro
      - ./database/data:/app/data/db
    networks:
      vina-network:
        aliases:
          - vina-db

  vina-scrapper:
    container_name: vina-scrapper
    build: ./news-scrapper/
    env_file: ./.env
    volumes:
      - ./news-scrapper/newspapers.txt:/app/newspapers.txt:ro
      - ./news-scrapper/tokenizers:/app/tokenizers:ro
    depends_on:
      vina-db:
        condition: service_started
    networks:
      vina-network:
        aliases:
          - vina-scrapper

  vina-server:
    container_name: vina-server
    restart: unless-stopped
    build: ./vina-server/
    env_file: ./.env
    ports:
      - "8080:8080"
    networks:
      vina-network:
        aliases:
          - vina-server
    depends_on:
      vina-db:
        condition: service_started

networks:
  vina-network:
    name: vina-network
    driver: bridge
